import { Inter } from 'next/font/google'
import './globals.css'
import { 
  ResponsiveContainer,
  ResponsiveHeader,
  ResponsiveFooter,
  ResponsiveBody
} from '@/components/components'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {  
  return (
    <html lang="en">
      <body className={inter.className}>
            <ResponsiveContainer>
                <ResponsiveHeader logo={'Jeruzael'}>
                    <Link href={'/projects'}>Projects</Link>
                    <Link href={'/contact'}>Contact</Link>
                    <Link href={'/resume'}>Resume</Link>                    
                </ResponsiveHeader>
                <ResponsiveBody>
                    {children}
                </ResponsiveBody>                
            </ResponsiveContainer>
            <ResponsiveFooter>
                <h1>Footer</h1>
            </ResponsiveFooter>
      </body>
    </html>
  )
}
